DB_PASSWORD=12345
DB_USERNAME=root
DB_ROOT_USERNAME=rrms
DB_NAME=rrms
PORT=8080
SECRET_KEY_CAPTCHA=0x4AAAAAAAkocny94-Ex4wStgWnpEPYJhd8

REDIS_HOST=redis-13684.c295.ap-southeast-1-1.ec2.redns.redis-cloud.com
REDIS_PORT=13684
REDIS_USERNAME=default
REDIS_PASSWORD=BdM0pUHgEJEzmTvgMSwboeCnCHfMhz48


JWT_SIGNER=BE6HM/oN7KIuLdNEoYjXYrLFSrGEX7bNywc9Z3AKkdGsHhbkJeM2XbqCKqfT0aqC

MY_GMAIL=quockkps31817@fpt.edu.vn
MY_PASSWORD_APP=aebpmtubuaomkywb

PAYPAL_ID=Aaz6DUZ3z6XxcN6_OZQbX6hoFxN12xWnvKg2wvcK_Fz-ab7VTypeJU_PIqW4rPbKRTWgPjmOrHH69G59
PAYPAL_SECRET=EERA0BTA7HmkHWg81Y1hFIwPMw1TH5o4QiuViWOlibSvto53ePiiWG4QNpTw4uzSOSLtfb5pjfxLAe_f

STRIPE_PUBLIC_KEY=pk_test_51POubLIe2vfQhSWEYarMBn27sc4ydF1n0nhgwSjgy66cojdCizekyBhLqjLpMyvKFmx4FV8BDaoOVCcjaftzhhDu00JImFrcBU
STRIPE_SECRET_KEY=sk_test_51POubLIe2vfQhSWEFwoQQkheiEKl1lg7ipnsD4GPsT1NnRvemMk0fveGgI0heSjWLavjNZlCe3KLWRviOBz60JyO00u2MgWDhw

momo_secret_key=SetA5RDnLHvt51AULf51DyauxUo3kDU6
dev_secret_key =SetA5RDnLHvt51AULf51DyauxUo3kDU6

vnpay_secretKey=GVN4SVUT6PITAULH61WSFT1UAW77CZQ1